run cloudfront

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -520,24 +520,24 @@ jobs:
             echo "${API_URL}"
             if curl "${API_URL}/api/status" | grep "ok"
             then
-              return 0
+              echo "Backend smoke test passed"
+              exit 0
             else
-              return 1
+              echo "Backend smoke test fail"
+              exit 1
             fi
       - run:
           name: Frontend smoke test.
           command: |
-            FE_STATIC_HOST=$(cat /home/circleciworkspace/fe_static_host)
-            FE_URL="https://$FE_STATIC_HOST/index.html"
-            REPONSE = $(eval curl -s $FE_URL)
-            if echo $RESPONSE | grep "View & Manage Employees" 
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
+            echo ${URL} 
+            if curl -s ${URL} | grep "Welcome"
             then
               echo "Frontend smoke test passed"
-              echo $REPONSE
-              return 0
+              exit 0
             else
               echo "Frontend smoke test fail"
-              return 1
+              exit 1
             fi
       # Here's where you will add some code to rollback on failure  
 
@@ -549,7 +549,6 @@ jobs:
       - run:
           name: Update cloudfront distribution
           command: |
-            lsb_release -a
             aws cloudformation deploy \
               --template-file .circleci/files/cloudfront.yml \
               --stack-name InitialStack \
@@ -608,9 +607,9 @@ workflows:
           requires: [run-migrations]
       - deploy-backend:
           requires: [run-migrations]
+      - cloudfront-update:
+          requires: [deploy-frontend]
       - smoke-test:
-          requires: [deploy-backend, deploy-frontend]
-      # - cloudfront-update:
-      #     requires: [smoke-test]
+          requires: [deploy-backend, cloudfront-update]
       # - cleanup:
       #     requires: [cloudfront-update]
